<?php
		//Generated by FactoryGenerator::generate() on 10/05/2019 12:52:19
abstract class FactoryLivre {

	public static function getFromTableLivre($id=0) {
		//Generated by FactoryGenerator::generateGetAllFromTable() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `livre`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > 0) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > 0) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table livre');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Livre($data['id'],$data['titre'],$data['sousTitre'],$data['resume'],$data['image'],$data['etat'],$data['edition'],$data['mot_cle'],$data['langue']);
		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEtat($etat=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `livre` ';
		if ($etat == 0) {
			$requete .= 'WHERE etat > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE etat = '.$etat.' ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$etat = array(':etat' => $etat);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($etat) || $etat > 0) {
			database::getInstance() -> bind($etat);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table livre');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Livre($data['id'],$data['titre'],$data['sousTitre'],$data['resume'],$data['image'],$data['etat'],$data['edition'],$data['mot_cle'],$data['langue']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEdition($edition=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `livre` ';
		if ($edition == 0) {
			$requete .= 'WHERE edition > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE edition = '.$edition.' ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$edition = array(':edition' => $edition);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($edition) || $edition > 0) {
			database::getInstance() -> bind($edition);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table livre');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Livre($data['id'],$data['titre'],$data['sousTitre'],$data['resume'],$data['image'],$data['etat'],$data['edition'],$data['mot_cle'],$data['langue']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableLangue($langue=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `livre` ';
		if ($langue == 0) {
			$requete .= 'WHERE langue > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE langue = '.$langue.' ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$langue = array(':langue' => $langue);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($langue) || $langue > 0) {
			database::getInstance() -> bind($langue);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table livre');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Livre($data['id'],$data['titre'],$data['sousTitre'],$data['resume'],$data['image'],$data['etat'],$data['edition'],$data['mot_cle'],$data['langue']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


}
?>