<?php
		//Generated by FactoryGenerator::generate() on 10/05/2019 12:52:19
abstract class FactoryEdition {

	public static function getFromTableEdition($id=0) {
		//Generated by FactoryGenerator::generateGetAllFromTable() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `edition`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > 0) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > 0) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table edition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Edition($data['id'],$data['date_publication'],$data['isbn'],$data['nb_page'],$data['couverture'],$data['livre'],$data['langue']);
		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableLivre($livre=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `edition` ';
		if ($livre == 0) {
			$requete .= 'WHERE livre > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE livre = '.$livre.' ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$livre = array(':livre' => $livre);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($livre) || $livre > 0) {
			database::getInstance() -> bind($livre);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table edition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Edition($data['id'],$data['date_publication'],$data['isbn'],$data['nb_page'],$data['couverture'],$data['livre'],$data['langue']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableLangue($langue=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 10/05/2019 12:52:19
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `edition` ';
		if ($langue == 0) {
			$requete .= 'WHERE langue > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE langue = '.$langue.' ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$langue = array(':langue' => $langue);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($langue) || $langue > 0) {
			database::getInstance() -> bind($langue);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table edition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Edition($data['id'],$data['date_publication'],$data['isbn'],$data['nb_page'],$data['couverture'],$data['livre'],$data['langue']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


}
?>